### ISSUE TITLE
Script timing out with "Cannot get config id ... binding does not exist."

### ISSUE THREAD

**Issue by brianwarner** [openhab-5iver/openHAB-utils#7]
Hi,
I'm attempting to install the latest snapshot (currently 2.5.6-20200524.091225-3.jar) on OH stable (2.5.5), and the script is timing out on the step "Installing unmanaged Z-Wave binding..." with this error appearing in the logs:

```
[ore.internal.binding.BindingResource] - Cannot get config id for binding id 'zwave', probably because binding does not exist.
```

I'm attempting to replace the 2.5.5 binding. Do you have any suggestions where I start on debugging?

**Comment by brianwarner** [comment]
Well, nevermind. :-) Restarted the system, and things came up as expected. Despite the error, it retrieved the new version of the binding and it started correctly.

I'll close this. Thanks for creating the script, it's nice to be able to pick up Chris' database updates so easily!

**Comment by 5iver** [comment]
You're welcome! I'll take a look, but nothing should have changed in this area. For some reason, the REST API was not reporting the zwave binding installed, hence the log entry. Glad it is working for you! Please let me know if it continues to occur when updating to another version of the binding.
